// examples/vue-graph/src/App.vue
<script setup lang="ts">
import GraphContainer from './GraphContainer.vue'
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <GraphContainer :count="count" />
  <h1>Vue + Depict</h1>

  <div class="card">
    <button type="button" @click="count++">count is {{ count }}</button>
    <p>
      Edit
      <code>components/Graph.vue</code> to test HMR
    </p>
  </div>

  <p class="read-the-docs">this is an example application to run depict in Vue.</p>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>

// examples/react-graph/src/App.tsx
import { useState } from 'react'
import './App.css'
import GraphContainer from './graph'

function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <div>
        <GraphContainer count={count} />
      </div>
      <h1>React + Depict</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        this is an example application to run depict in React.
      </p>
    </>
  )
}

export default App
