// examples/svelte-graph/src/lib/Graph.svelte
<script lang="ts">
  import { Depict } from "@pattaya/depict";
  import { onMount } from "svelte";
  import { MsgUpdateSvelteState } from "./msg";

  const worker = new Worker(new URL("./worker.ts", import.meta.url), {
    type: "module",
  });

  let { count } = $props();

  $effect(() => {
    worker.postMessage({ type: MsgUpdateSvelteState, msg: count });
  });

  let graph: Depict | undefined = $state(undefined);
  let rootRef: HTMLDivElement | undefined;

  onMount(() => {
    if (!graph) {
      if (!rootRef) return;
      graph = new Depict({
        root: rootRef,
        maxLayers: 3,
        worker,
      });
      graph.start();
    }

    return () => graph?.destory();
  });
</script>

<div class="graph" bind:this={rootRef}></div>

<style>
  .graph {
    position: relative;
    width: 600px;
    height: 400px;
    border: 1px solid #333;
    border-radius: 20px;
  }
</style>

// examples/react-graph/src/graph.tsx
import { Depict } from "@pattaya/depict";
import { useEffect, useRef, useState } from "react";

const worker = new Worker(new URL('./worker.ts', import.meta.url), {
  type: "module"
});

export interface GraphContainerProps {
  count: number;
};

function GraphContainer({ count }: GraphContainerProps) {
  const rootRef = useRef<HTMLDivElement>(null);
  const [graph, setGraph] = useState<Depict | undefined>(undefined);

  useEffect(() => {
    let g = graph;
    if (!g) {
      const canvas = rootRef.current;
      if (canvas === null) return;
      g = new Depict({
        root: canvas,
        maxLayers: 3,
        worker,
      });
      setGraph(g);
      g.start();
    }

    return () => g?.destory();
  }, []);

  useEffect(() => {
    worker.postMessage({ type: 1, msg: count });
  }, [count]);

  return (
    <div
      style={{
        position: "relative",
        width: "600px",
        height: "400px",
        border: "1px solid #333",
        borderRadius: "20px",
        // overflow: "hidden"
      }}
      ref={rootRef}
    ></div>
  )
}

export default GraphContainer;
