// examples/svelte-graph/src/App.svelte
<script lang="ts">
  import Graph from "./GraphContainer.svelte";

  let count: number = $state(0);
  const increment = () => {
    count += 1;
  };
</script>

<main>
  <Graph {count} />
  <h1>Depict + Svelte</h1>

  <div class="card">
    <button onclick={increment}>
      count is {count}
    </button>
  </div>

  <p>
    Edit
    <code>lib/Graph.svelte</code> to start
  </p>

  <p class="read-the-docs">
    this is an example application to run depict in Svelte.
  </p>
</main>

<style>
  .read-the-docs {
    color: #888;
  }
</style>

// examples/vue-graph/src/App.vue
<script setup lang="ts">
import GraphContainer from './GraphContainer.vue'
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <GraphContainer :count="count" />
  <h1>Vue + Depict</h1>

  <div class="card">
    <button type="button" @click="count++">count is {{ count }}</button>
    <p>
      Edit
      <code>components/Graph.vue</code> to test HMR
    </p>
  </div>

  <p class="read-the-docs">this is an example application to run depict in Vue.</p>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>
